# Generated by Django 3.0.6 on 2020-05-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expense_income',
            field=models.ManyToManyField(to='planner.PlannedExpense'),
        ),
        migrations.AddField(
            model_name='budget',
            name='planned_income',
            field=models.ManyToManyField(to='planner.PlannedIncome'),
        ),
    ]
