# Generated by Django 3.0.6 on 2020-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20200507_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='expenses',
        ),
        migrations.AddField(
            model_name='budget',
            name='expenses',
            field=models.ManyToManyField(to='planner.Expense'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='incomes',
        ),
        migrations.AddField(
            model_name='budget',
            name='incomes',
            field=models.ManyToManyField(to='planner.Income'),
        ),
    ]
