# Generated by Django 3.0.6 on 2020-05-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20200508_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='expense_income',
            new_name='planned_expense',
        ),
    ]
